import turtle as trtl
trtl.colormode(255)

# screen setup
wn = trtl.Screen()
wn.setup(width = 750, height= 550)
wn.bgcolor("skyblue")

# basic layout of park
layout = trtl.Turtle()
layout.turtlesize(0.1)
layout.penup()
layout.goto(-375,-300)
layout.begin_fill()
layout.color(50,180,20)
layout.fillcolor(50,180, 20)
layout.pendown()
layout.left(90)
layout.forward(350)
layout.right(90)
layout.forward(750)
layout.right(90)
layout.forward(350)
layout.penup()
layout.end_fill()
layout.goto(-375,0)
layout.pensize(50)
layout.color(36,36,36)
layout.pendown()
layout.right(90)
layout.circle(500, -70)


# tree function
def tree_one(x,y):
    tree = trtl.Turtle()
    tree.penup()
    tree.goto(x,y)
    tree.pendown()
    tree.setheading(90)
    tree.begin_fill()
    tree.color(92,64,51)
    tree.fillcolor(92,64,51)
    tree.forward(70)
    tree.right(90)
    tree.forward(20)
    tree.right(90)
    tree.forward(70)
    tree.end_fill()
    tree.penup()
    tree.goto(x, y+50)
    tree.setheading(116)
    tree.begin_fill()
    tree.pendown()
    tree.forward(20)
    tree.left(90)
    tree.forward(5)
    tree.left(90)
    tree.forward(30)
    tree.penup()
    tree.end_fill()
    tree.fillcolor(6, 64, 43)
    tree.goto(x-20, y+60)
    tree.pendown()
    tree.color(6,64,43)
    for i in range(5):
        tree.begin_fill()
        tree.setheading(0)
        tree.circle(10)
        tree.penup()
        tree.goto(tree.xcor()+15, y+60)
        tree.pendown()
        tree.end_fill()
    tree.penup()
    tree.goto(x-10, y + 72)
    tree.pendown()
    for i in range(4):
        tree.begin_fill()
        tree.setheading(0)
        tree.circle(10)
        tree.penup()
        tree.goto(tree.xcor()+12, y+72)
        tree.pendown()
        tree.end_fill()
    tree.penup()
    tree.goto(x, y+85)
    tree.pendown()
    for i in range(2):
        tree.begin_fill()
        tree.setheading(0)
        tree.circle(10)
        tree.penup()
        tree.goto(tree.xcor()+15, y+85)
        tree.pendown()
        tree.end_fill()

tree_one(-300, 20)



# mainloop    
wn.mainloop()
